/** Every user-visible UI string added from M2 on, kept in one place for M5 i18n extraction (spec §17). */
export const strings = {
  commands: {
    failed: (title: string, error: unknown) =>
      `${title} failed: ${error instanceof Error ? error.message : String(error)}`,
    onOff: (on: boolean) => (on ? "currently on" : "currently off"),
    loopLimit: (limit: number) => `limit ${limit}`,
    current: "current",
    copyFailed: "Couldn't copy the output to the clipboard.",
  },
  limits: {
    tooLarge: "This tab is larger than 64 MB. JSLab stops saving and running it until it's smaller.",
  },
  // Carried item T11-m4: a tab action (create/close/reopen/...) that Main rejects reports a status message
  // instead of leaving an unhandled rejection.
  tabs: {
    actionFailed: (error: unknown) =>
      `Couldn't complete that action: ${error instanceof Error ? error.message : String(error)}`,
    list: "Tabs",
    newTab: "New Tab",
    close: (title: string) => `Close ${title}`,
    unsaved: "Unsaved changes",
    rename: "Rename…",
    closeOne: "Close",
    closeOthers: "Close Others",
    closeToRight: "Close to the Right",
    reveal: "Reveal in Finder",
    copyPath: "Copy Path",
    renameTitle: "Rename Tab",
    renameLabel: "Tab name",
    renameHelp: "Leave empty to use the first line of code as the title.",
    cancel: "Cancel",
    save: "Rename",
  },
  files: {
    saved: (name: string) => `Saved ${name}`,
    saveFailed: (error: string) => `Couldn't save: ${error}`,
    saveChanges: (name: string) => `Save changes to ${name}?`,
    saveChangesDetail: "Your changes will be lost if you don't save them.",
    dontSave: "Don't Save",
    cancel: "Cancel",
    save: "Save",
    closeTitle: (name: string) => `Close "${name}"?`,
    closeDetail: "Its contents are kept in Reopen Closed Tab.",
    close: "Close",
    largeTitle: "Open a large file?",
    large: (name: string, size: string) => `${name} is ${size}. Large files can make JSLab slow.`,
    open: "Open",
    pasteTitle: "Paste a large amount of text?",
    paste: (size: string) => `Pasting ${size} may make JSLab slow. Continue?`,
    pasteButton: "Paste",
    locationTitle: "Save to this location?",
    location: (path: string) => `Save as ${path}?`,
    notText: (name: string) => `${name} isn't a text file.`,
    tooLarge: (name: string) => `${name} is larger than 50 MB and can't be opened.`,
    folderDrop: "Dropping a folder sets the working directory, which arrives with working directories.",
  },
  fonts: {
    fallback: (font: string) => `Font "${font}" isn't available; using JetBrains Mono.`,
    // m-2 (fix round 1): the default font itself can fail its own check; don't claim to "fall back to
    // JetBrains Mono" from JetBrains Mono.
    bundledUnavailable: "The bundled code font couldn't load; using the system monospace font.",
  },
  shell: {
    run: "Run",
    stop: "Stop",
    autoRun: "Auto Run",
    activity: "Activity",
    running: "Running",
    on: "on",
    off: "off",
    snippets: "Snippets",
    npm: "NPM Packages",
    aiChat: "AI Chat",
    settings: "Settings",
    laterMilestone: "Arrives in a later version",
    safeMode: "Safe Mode",
    sideBarPlaceholder: "This panel arrives in a later version.",
    split: { horizontal: "Side by side", vertical: "Stacked" },
    cursor: (line: number, column: number) => `Ln ${line}, Col ${column}`,
    runtime: "Runtime",
    language: "Language",
  },
  output: {
    filters: { all: "All", results: "Results", logs: "Logs", errors: "Errors" },
    filterLabel: "Output filter",
    copyAll: "Copy All",
    clear: "Clear",
    jumpToLine: (line: number) => `Go to line ${line}`,
    truncated: (dropped: number) =>
      `Output truncated: ${dropped} more entries were dropped. Raise the limit in Settings → Advanced.`,
    region: "Output",
    lastSuccessfulRun: "Last successful run",
    copied: "Copied",
    copyFailed: "Couldn't copy",
  },
} as const;
