/** Every user-visible UI string added from M2 on, kept in one place for M5 i18n extraction (spec §17). */
export const strings = {
  commands: {
    failed: (title: string, error: unknown) =>
      `${title} failed: ${error instanceof Error ? error.message : String(error)}`,
    onOff: (on: boolean) => (on ? "currently on" : "currently off"),
    loopLimit: (limit: number) => `limit ${limit}`,
    current: "current",
    copyFailed: "Couldn't copy the output to the clipboard.",
  },
  limits: {
    tooLarge: "This tab is larger than 64 MB. JSLab stops saving and running it until it's smaller.",
  },
  format: {
    failed: (message: string) => `Couldn't format: ${message}`,
    busy: "Formatting…",
    timedOut: "formatting took too long, so the formatter was restarted",
    restarted: "the formatter was restarted",
    crashed: "the formatter stopped unexpectedly",
    disposed: "the formatter was closed",
  },
  // Carried item T11-m4: a tab action (create/close/reopen/...) that Main rejects reports a status message
  // instead of leaving an unhandled rejection.
  tabs: {
    actionFailed: (error: unknown) =>
      `Couldn't complete that action: ${error instanceof Error ? error.message : String(error)}`,
    list: "Tabs",
    newTab: "New Tab",
    close: (title: string) => `Close ${title}`,
    unsaved: "Unsaved changes",
    rename: "Rename…",
    closeOne: "Close",
    closeOthers: "Close Others",
    closeToRight: "Close to the Right",
    reveal: "Reveal in Finder",
    copyPath: "Copy Path",
    renameTitle: "Rename Tab",
    renameLabel: "Tab name",
    renameHelp: "Leave empty to use the first line of code as the title.",
    cancel: "Cancel",
    save: "Rename",
  },
  files: {
    saved: (name: string) => `Saved ${name}`,
    saveFailed: (error: string) => `Couldn't save: ${error}`,
    saveChanges: (name: string) => `Save changes to ${name}?`,
    saveChangesDetail: "Your changes will be lost if you don't save them.",
    dontSave: "Don't Save",
    cancel: "Cancel",
    save: "Save",
    closeTitle: (name: string) => `Close "${name}"?`,
    closeDetail: "Its contents are kept in Reopen Closed Tab.",
    close: "Close",
    largeTitle: "Open a large file?",
    large: (name: string, size: string) => `${name} is ${size}. Large files can make JSLab slow.`,
    open: "Open",
    pasteTitle: "Paste a large amount of text?",
    paste: (size: string) => `Pasting ${size} may make JSLab slow. Continue?`,
    pasteButton: "Paste",
    locationTitle: "Save to this location?",
    location: (path: string) => `Save as ${path}?`,
    notText: (name: string) => `${name} isn't a text file.`,
    tooLarge: (name: string) => `${name} is larger than 50 MB and can't be opened.`,
    folderDrop: "Dropping a folder sets the working directory, which arrives with working directories.",
  },
  fonts: {
    fallback: (font: string) => `Font "${font}" isn't available; using JetBrains Mono.`,
    // m-2 (fix round 1): the default font itself can fail its own check; don't claim to "fall back to
    // JetBrains Mono" from JetBrains Mono.
    bundledUnavailable: "The bundled code font couldn't load; using the system monospace font.",
  },
  shell: {
    run: "Run",
    stop: "Stop",
    autoRun: "Auto Run",
    activity: "Activity",
    running: "Running",
    on: "on",
    off: "off",
    snippets: "Snippets",
    npm: "NPM Packages",
    aiChat: "AI Chat",
    settings: "Settings",
    laterMilestone: "Arrives in a later version",
    safeMode: "Safe Mode",
    sideBarPlaceholder: "This panel arrives in a later version.",
    split: { horizontal: "Side by side", vertical: "Stacked" },
    cursor: (line: number, column: number) => `Ln ${line}, Col ${column}`,
    runtime: "Runtime",
    language: "Language",
    /** A button's tooltip with its shortcut, when it has one (FB-m3). */
    withKeys: (label: string, keys: string | null) => (keys ? `${label} (${keys})` : label),
    dismiss: (message: string) => `Dismiss: ${message}`,
    unresponsive: {
      title: "This tab isn't responding",
      body: "Your code has been busy for a few seconds without responding. You can kill it, or keep waiting.",
      wait: "Wait",
      kill: "Kill",
    },
    safeModeBanner: {
      crashLoop: "JSLab didn't shut down cleanly while running code. Auto Run is paused for this session.",
      manual: "Safe Mode: restarted from Help → Restart in Safe Mode. Auto Run is paused for this session.",
      shift: "Safe Mode: Shift was held at launch. Auto Run is paused for this session.",
    },
    runState: {
      /** The Run chord follows the effective bindings; omits the keycap when the binding was removed. */
      safeModePaused: (keys: string | null) => (keys ? `Safe Mode: press ${keys} to run` : "Safe Mode: paused"),
      paused: (keys: string | null) => (keys ? `Paused: press ${keys} to run` : "Paused"),
      running: "Running…",
      settled: (handles: number) => `Running: ${handles} active ${handles === 1 ? "handle" : "handles"}`,
      stopping: "Stopping…",
      stopped: "Stopped",
      killed: "Run killed",
      failed: "Failed",
      unresponsive: "Not responding",
    },
  },
  notices: {
    copyDebugLog: "Copy Debug Log",
  },
  startup: {
    failed: (message: string) => `JSLab failed to start: ${message}`,
    retry: "Try Again",
  },
  palette: {
    label: "Command palette",
    categories: {
      run: "Run",
      file: "File",
      tab: "Tabs",
      edit: "Edit",
      format: "Format",
      view: "View",
      runtime: "Runtime",
      language: "Language",
      theme: "Theme",
      help: "Help",
      app: "JSLab",
    },
    placeholder: "Type a command",
    context: { editor: "Editor", output: "Output" },
    themeItem: (name: string) => `Theme: ${name}`,
    empty: "No matching commands",
    footer: {
      keys: { run: "↵", move: "↑↓", close: "esc" },
      run: "run",
      move: "move",
      close: "close",
    },
  },
  output: {
    filters: { all: "All", results: "Results", logs: "Logs", errors: "Errors" },
    filterLabel: "Output filter",
    copyAll: "Copy All",
    clear: "Clear",
    jumpToLine: (line: number) => `Go to line ${line}`,
    truncated: (dropped: number) =>
      `Output truncated: ${dropped} more entries were dropped. Raise the limit in Settings → Advanced.`,
    region: "Output",
    lastSuccessfulRun: "Last successful run",
    copied: "Copied",
    copyFailed: "Couldn't copy",
    noMatches: "No entries match this filter",
    showAll: "Show all",
    noOutput: (keys: string | null) => (keys ? `No output yet — press ${keys}` : "No output yet"),
    tableIndex: "(index)",
    uncaughtInPromise: "Uncaught (in promise) ",
    internalFrames: (count: number) => `${count} internal frames`,
    /** A clickable stack-frame line (RR2-m5). */
    frame: (fn: string, line: number, column: number) => `at ${fn} (L${line}:${column})`,
    anonymous: "<anonymous>",
  },
  settings: {
    windowTitle: "Settings",
    search: "Search settings",
    results: "Search results",
    restartRequired: "Restart required",
    tabs: {
      general: "General",
      editor: "Editor",
      formatting: "Formatting",
      appearance: "Appearance",
      advanced: "Advanced",
    },
    groups: {
      dark: "Dark",
      light: "Light",
      bundled: "Bundled",
      monospace: "Installed monospace",
      installed: "Installed",
    },
    loadingFonts: "Loading installed fonts…",
    fontsUnavailable: "Couldn't load installed fonts",
    openDataFolder: "Open Data Folder",
    resetAll: "Reset All Settings…",
    confirmReset: "Confirm Reset",
    restartSafeMode: "Restart in Safe Mode",
    loadFailed: (message: string) => `Settings failed to load: ${message}`,
    fields: {
      "run.autoRun": { label: "Auto Run", help: "Run code automatically as you type." },
      "run.autoLog": { label: "Auto Log", help: "Show the value of each top-level expression." },
      "run.defaultRuntime": {
        label: "Default Runtime",
        help: "Runtime for new tabs. Browser runtimes arrive in a later version; until then new tabs use Bun.",
      },
      "run.defaultLanguage": { label: "Default Language", help: "Language for new tabs." },
      "run.formatOnRun": {
        label: "Format on Run",
        help: "Format code with Prettier before each run, unless you are typing.",
      },
      "tabs.confirmClose": { label: "Confirm Close", help: "Ask before closing any tab." },
      "app.uiLanguage": {
        label: "Language",
        help: "Language of menus and panels. More languages arrive in a later version.",
      },
      "editor.lineNumbers": { label: "Line Numbers", help: "Show line numbers in the gutter." },
      "editor.lineWrap": { label: "Line Wrap", help: "Wrap long lines to the editor width." },
      "editor.vimKeys": { label: "Vim Keys", help: "Edit with Vim key bindings. ⌘R still runs in every mode." },
      "editor.closeBrackets": {
        label: "Close Brackets",
        help: "Insert the closing bracket or quote when you type the opening one.",
      },
      "editor.invisibles": { label: "Invisibles", help: "Render spaces and tabs." },
      "editor.activeLine": { label: "Active Line", help: "Highlight the line with the cursor." },
      "editor.autocomplete": { label: "Autocomplete", help: "Suggest completions while you type." },
      "editor.linting": { label: "Linting", help: "Show TypeScript diagnostics inline. Never blocks running code." },
      "editor.hoverInfo": { label: "Hover Info", help: "Show type information when hovering over code." },
      "editor.hoverDelayMs": {
        label: "Hover Delay",
        help: "Milliseconds before hover information appears (100–2000).",
      },
      "editor.signatures": { label: "Signatures", help: "Show parameter hints while typing a call." },
      "editor.formatOnSave": { label: "Format on Save", help: "Format code with Prettier before saving a file." },
      "editor.minimap": { label: "Minimap", help: "Show a code overview next to the scroll bar." },
      "prettier.printWidth": { label: "Print Width", help: "Line length Prettier wraps at." },
      "prettier.tabWidth": { label: "Tab Width", help: "Spaces per indentation level." },
      "prettier.useTabs": { label: "Use Tabs", help: "Indent with tabs instead of spaces." },
      "prettier.semi": { label: "Semicolons", help: "Add a semicolon at the end of every statement." },
      "prettier.singleQuote": { label: "Single Quotes", help: "Use single quotes instead of double quotes." },
      "prettier.quoteProps": { label: "Quote Props", help: "When to quote object property names." },
      "prettier.jsxSingleQuote": { label: "JSX Single Quotes", help: "Use single quotes in JSX attributes." },
      "prettier.trailingComma": { label: "Trailing Commas", help: "Where to add trailing commas." },
      "prettier.bracketSpacing": { label: "Bracket Spacing", help: "Put spaces between brackets in object literals." },
      "prettier.bracketSameLine": {
        label: "Bracket Same Line",
        help: "Put the > of a multi-line JSX element at the end of the last line.",
      },
      "prettier.arrowParens": {
        label: "Arrow Parens",
        help: "Include parentheses around a sole arrow function parameter.",
      },
      "appearance.theme": { label: "Theme", help: "Color theme for the editor and the window." },
      "appearance.followSystem": {
        label: "Follow System Appearance",
        help: "Switch between the light and dark themes below with macOS.",
      },
      "appearance.lightTheme": { label: "Light Theme", help: "Theme used in light mode when following the system." },
      "appearance.darkTheme": { label: "Dark Theme", help: "Theme used in dark mode when following the system." },
      "appearance.font": {
        label: "Font",
        help: "Font for the editor and output. Bundled fonts are listed first, then installed fonts.",
      },
      "appearance.fontSize": { label: "Font Size", help: "Font size for the editor and output (8–72)." },
      "appearance.fontLigatures": {
        label: "Font Ligatures",
        help: "Combine character pairs like => into ligatures when the font supports them.",
      },
      "appearance.uiScale": {
        label: "Zoom",
        help: "Scales the editor, output and side bar. Also changed by ⌘= and ⌘−.",
      },
      "view.tabBarForSingleTab": { label: "Tab Bar", help: "Show the tab bar even when only one tab is open." },
      "view.activityBar": { label: "Activity Bar", help: "Show the activity bar on the left." },
      "view.statusBar": { label: "Status Bar", help: "Show the status bar at the bottom." },
      "view.sideBar": { label: "Side Bar", help: "Show the side bar." },
      "view.layout": { label: "Layout", help: "Split direction for new tabs." },
      "output.highlighting": { label: "Output Highlighting", help: "Color values in the output by type." },
      "output.showLineNumbers": {
        label: "Output Line Numbers",
        help: "Show the source line next to each output entry.",
      },
      "run.showUndefined": { label: "Show Undefined", help: "Show expressions whose value is undefined." },
      "run.loopProtection": {
        label: "Loop Protection",
        help: "Stop loops that run more iterations than the limit below.",
      },
      "run.loopProtectionMaxIterations": {
        label: "Loop Limit",
        help: "Iterations before loop protection stops a loop (100–10,000,000).",
      },
      "run.autoRunDelayMs": {
        label: "Auto Run Delay",
        help: "Milliseconds after you stop typing before code runs (0–5000).",
      },
      "run.unresponsiveTimeoutMs": {
        label: "Unresponsive Timeout",
        help: "Milliseconds without a heartbeat before JSLab offers to kill a run (1000–60000).",
      },
      "output.maxEntries": {
        label: "Output Limit",
        help: "Most entries kept per run before output is truncated (100–100,000).",
      },
      "updates.auto": { label: "Automatic Updates", help: "Download and install updates automatically." },
      "updates.channel": {
        label: "Update Channel",
        help: "Stable releases, or canary builds with the newest changes.",
      },
    } as Record<string, { label: string; help: string }>,
    options: {
      runtime: { "browser-node": "Browser & Node APIs", bun: "Bun", browser: "Browser" },
      language: { typescript: "TypeScript", javascript: "JavaScript", tsx: "TSX", jsx: "JSX" },
      uiLanguage: { system: "System", en: "English", es: "Español", ja: "日本語", zh: "中文", pt: "Português" },
      quoteProps: { "as-needed": "As needed", consistent: "Consistent", preserve: "Preserve" },
      trailingComma: { all: "All", es5: "ES5", none: "None" },
      arrowParens: { always: "Always", avoid: "Avoid" },
      layout: { horizontal: "Horizontal", vertical: "Vertical" },
      channel: { stable: "Stable", canary: "Canary" },
    },
  },
} as const;
